import secrets, string


class DBClusterApiKeyService:
    """
    API key generator for Qdrant Cluster configurations.
    """

    @staticmethod
    def generate(length: int = 32) -> str:
        """
        Generates a 32-character alphanumeric key similar to those
        automatically generated by Qdrant instances.

        :param length: The length of the API key to be generated.
            Default is 32.
        :return: A securely generated random alphanumeric string.
        """

        characters = string.ascii_letters + string.digits
        secure_random_string = ''.join(
            secrets.choice(characters) for i in range(length))
        return secure_random_string
